// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.DSConn;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240903103233_initCreate")]
    partial class initCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication4.Models.Contract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("EmpRef")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("empsId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("empsId");

                    b.ToTable("Contract", "EmpDet");
                });

            modelBuilder.Entity("WebApplication4.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentHead")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("Department", "EmpDet");
                });

            modelBuilder.Entity("WebApplication4.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DepRef")
                        .HasColumnType("int");

                    b.Property<int?>("DepsID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosRef")
                        .HasColumnType("int");

                    b.Property<int>("ProRef")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("posID")
                        .HasColumnType("int");

                    b.Property<int?>("projsID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepsID");

                    b.HasIndex("posID");

                    b.HasIndex("projsID");

                    b.ToTable("Employee", "EmpDet");
                });

            modelBuilder.Entity("WebApplication4.Models.Invoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal (18, 0)");

                    b.Property<int>("EmpRef")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceDescription")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateOnly?>("InvoiceDue")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int?>("empsId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("empsId");

                    b.ToTable("Invoice", "EmpDet");
                });

            modelBuilder.Entity("WebApplication4.Models.LeaveRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EmpRef")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("NoRequest")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int?>("empsId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("empsId");

                    b.ToTable("LeaveRequest", "EmpDet");
                });

            modelBuilder.Entity("WebApplication4.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("PositionDescription")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PositionTitle")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("Position", "EmpDet");
                });

            modelBuilder.Entity("WebApplication4.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("Project", "EmpDet");
                });

            modelBuilder.Entity("WebApplication4.Models.Contract", b =>
                {
                    b.HasOne("WebApplication4.Models.Employee", "emps")
                        .WithMany()
                        .HasForeignKey("empsId");

                    b.Navigation("emps");
                });

            modelBuilder.Entity("WebApplication4.Models.Employee", b =>
                {
                    b.HasOne("WebApplication4.Models.Department", "Deps")
                        .WithMany()
                        .HasForeignKey("DepsID");

                    b.HasOne("WebApplication4.Models.Position", "pos")
                        .WithMany()
                        .HasForeignKey("posID");

                    b.HasOne("WebApplication4.Models.Project", "projs")
                        .WithMany()
                        .HasForeignKey("projsID");

                    b.Navigation("Deps");

                    b.Navigation("pos");

                    b.Navigation("projs");
                });

            modelBuilder.Entity("WebApplication4.Models.Invoice", b =>
                {
                    b.HasOne("WebApplication4.Models.Employee", "emps")
                        .WithMany()
                        .HasForeignKey("empsId");

                    b.Navigation("emps");
                });

            modelBuilder.Entity("WebApplication4.Models.LeaveRequest", b =>
                {
                    b.HasOne("WebApplication4.Models.Employee", "emps")
                        .WithMany()
                        .HasForeignKey("empsId");

                    b.Navigation("emps");
                });
#pragma warning restore 612, 618
        }
    }
}
